#!/bin/bash
PREFIX=$(cd "$(dirname "$0")"; pwd)
BASE=$PREFIX/read_in_life_api

cd $BASE
if [ "$1" = "serve" ]; then
    echo "starting...."
    exec python -u $BASE/lib/serve/serve.py
else
    exec "$@"
fi
